// API request types are always imported from shared, never redefined (CLAUDE.md).
export {
  attachQualificationReportRequestSchema,
  closeMaintenanceTaskRequestSchema,
  completePmTaskRequestSchema,
  createCalibrationScheduleRequestSchema,
  createEquipmentRequestSchema,
  createLogbookAmendmentRequestSchema,
  createQualificationRecordRequestSchema,
  dispositionCalibrationRequestSchema,
  listEquipmentQuerySchema,
  logBreakdownRequestSchema,
  logCleaningRequestSchema,
  logUsageStartRequestSchema,
  logUsageStopRequestSchema,
  recordCalibrationResultRequestSchema,
  transitionEquipmentStatusRequestSchema,
  updateEquipmentRequestSchema,
  upsertPmPlanRequestSchema,
  verifyCalibrationRequestSchema,
  verifyMaintenanceTaskRequestSchema,
  type AttachQualificationReportRequest,
  type CloseMaintenanceTaskRequest,
  type CompletePmTaskRequest,
  type CreateCalibrationScheduleRequest,
  type CreateEquipmentRequest,
  type CreateLogbookAmendmentRequest,
  type CreateQualificationRecordRequest,
  type DispositionCalibrationRequest,
  type ListEquipmentQuery,
  type LogBreakdownRequest,
  type LogCleaningRequest,
  type LogUsageStartRequest,
  type LogUsageStopRequest,
  type RecordCalibrationResultRequest,
  type TransitionEquipmentStatusRequest,
  type UpdateEquipmentRequest,
  type UpsertPmPlanRequest,
  type VerifyCalibrationRequest,
  type VerifyMaintenanceTaskRequest,
} from '@pharmaqms/shared';
